import Openmath.Target
import Openmath.Proofs.AdjacentHubs
import Openmath.Proofs.BipartiteBalance
import Openmath.Proofs.BipartiteFive
import Openmath.Proofs.Compat
import Openmath.Proofs.Counting
import Openmath.Proofs.CutGluing
import Openmath.Proofs.DensityCore
import Openmath.Proofs.DoubleWheel
import Openmath.Proofs.Extension
import Openmath.Proofs.Final
import Openmath.Proofs.Five
import Openmath.Proofs.IncidenceHubs
import Openmath.Proofs.LatinIncidence
import Openmath.Proofs.MatchingSubdivision
import Openmath.Proofs.QB4.Core
import Openmath.Proofs.QB4.Defs
import Openmath.Proofs.QB4.FourFactor
import Openmath.Proofs.QB4.Main
import Openmath.Proofs.QB4.Reductions
import Openmath.Proofs.QB4.Statement
import Openmath.Proofs.QB5.Block
import Openmath.Proofs.QB5.C2Hub
import Openmath.Proofs.QB5.C2Petals
import Openmath.Proofs.QB5.C2TwoBlock
import Openmath.Proofs.QB5.CaseB
import Openmath.Proofs.QB5.Cover
import Openmath.Proofs.QB5.CoverCheck
import Openmath.Proofs.QB5.CoverCheck1
import Openmath.Proofs.QB5.CoverCheck2
import Openmath.Proofs.QB5.CoverCheck3
import Openmath.Proofs.QB5.Defs
import Openmath.Proofs.QB5.E5
import Openmath.Proofs.QB5.KL1
import Openmath.Proofs.QB5.KL1Merge
import Openmath.Proofs.QB5.Main
import Openmath.Proofs.QB5.PairCriterion
import Openmath.Proofs.QB5.Statement
import Openmath.Proofs.RegularFive
import Openmath.Proofs.RegularFive18
import Openmath.Proofs.RimDensity
import Openmath.Proofs.RimStrip
import Openmath.Proofs.SmallExact
import Openmath.Proofs.TopFive
import Openmath.Proofs.TwoHub
import Openmath.Proofs.TwoHubFamily

/-! Root module. Imports the statement and every proof
    file, so `lake build` checks all of them. -/
