#!/bin/bash
# reg5n16 census driver. Every 5-regular graph on 16 vertices, generated by geng with pair pruning
# (code/geng_pp), split into MOD=20000 res/mod shards, run in the fixed shuffled order of
# data/shard_order.txt by WORKERS parallel workers. Resumable: done shards are skipped.
# Stops taking shards at 06:10 EDT, kills running shards at 06:13:30, then writes REG5N16.md.
# Start: cd <lane>; nohup nice -n 10 bash code/driver.sh >> logs/driver.log 2>&1 &
# Graceful stop (no new shards): touch <lane>/STOP. Hard stop: see JOBS.md.
set -u
LANE="$(cd "$(dirname "$0")/.." && pwd)"
MOD=20000
WORKERS="${WORKERS:-13}"
STOP_NEW=$(date -j -f '%Y-%m-%d %H:%M:%S' '2026-10-06 13:00:00' +%s)
HARD=$(date -j -f '%Y-%m-%d %H:%M:%S' '2026-10-06 13:05:00' +%s)
export LANE MOD STOP_NEW HARD
echo "driver start $(date '+%Y-%m-%d %H:%M:%S %Z') pid=$$ workers=$WORKERS mod=$MOD nice=$(ps -o nice= -p $$)"
shasum -a 256 "$LANE/code/geng_pp" "$LANE/code/pairprune.c" "$(cat "$LANE/code/CURRENT_BIN")"
xargs -P "$WORKERS" -n 1 /bin/bash "$LANE/code/worker.sh" < "$LANE/data/shard_order.txt"
echo "driver shards finished $(date '+%Y-%m-%d %H:%M:%S %Z') done=$(/bin/ls "$LANE/logs/shards" | grep -c '\.done$')"
timeout 40 /bin/bash "$LANE/code/collect.sh" --quick
echo "driver end $(date '+%Y-%m-%d %H:%M:%S %Z')"
